# Generated by Django 4.1.4 on 2023-03-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='workout',
        ),
    ]
