# Generated by Django 4.1.4 on 2023-03-23 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_post_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecompleted',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
