# Generated by Django 4.1.4 on 2023-03-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_alter_exercisecompleted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.workout'),
        ),
    ]
