# Generated by Django 4.1.4 on 2023-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_post_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
    ]
